name: Run in Docker
on:
  workflow_dispatch:
    
jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
        
      - name: verify python version
        run: python --version
        
      - name: run script
        run: python APP/HELLO.py    