name: trigger on event
on:
  push:
    branches:
      - "main"
  
  pull_request:
    branches:
      - "main"

jobs:
  log-event:
    runs-on: ubuntu-latest
    steps:
      - name: print event name
        run: |
         echo "event triggered:" $GITHUB_EVENT_NAME
        shell: bash

      - name: show branch
        run: |
         echo "branch:" $GITHUB_REF
