name: Manual and Scheduled Workflow

on:
  
  workflow_dispatch:
    inputs:
      manual:
        description: 'that will run manual type ok'
        required: true       

  
  schedule:
    - cron: '3 * * * *'  

jobs:
  run-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Show Current Date and Time
        run: date
        shell: bash 
    
